Adds mean squared value summary statistics
stan-dev/posteriordb pull request #258
Opened 2024-05-30 09:08 UTC by JTorgander

Adding summary statistics for mean squared values of the reference posteriors. Additionally, the summary statistic "mean" is renamed to "mean_value".

2024-06-01 08:37 UTC, MansMeg requested changes
Please remove the .DS_Store files, then Im happy to merge.

2024-06-01 08:37 UTC, MansMeg commented on posterior_database/reference_posteriors/summary_statistics/mean_squared_value/info/.DS_Store
You have accidentaly committed .DS_Store files. Please remove these.

2024-06-03 14:17 UTC, JTorgander commented on posterior_database/reference_posteriors/summary_statistics/mean_squared_value/info/.DS_Store
Both files are removed now

2024-06-03 14:19 UTC, MansMeg approved these changes

2024-06-03 14:19 UTC, merged